<!DOCTYPE html>
<html lang="es">
<head>
    <link rel="stylesheet" href="<?php BASE_URL; ?>css/styles.css">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>MVC HTACCES</title>
</head>
<body>
	<?php echo BASE_URL; ?>
    <div id="front">
    </div>
    <div id="footer" align="center">
        <a href="plataform/">plataformas</a>
    </div>
</body>
</html>
